icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"
max_vol = 100

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
format = " $icon {$active_port |}"
max_vol = 100
[block.active_port_mappings]
"analog-input-rear-mic" = "" # Mapping to an empty string makes `$active_port` absent
"analog-input-front-mic" = "ERR!"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %I:%M %p') "

[[block]]
block = "battery"
format = " $icon $percentage "
interval = 1

