#!/usr/bin/env bash

STARSHIP_CONFIG="$HOME/.config/starship.toml"
PALETTE_FILE="/tmp/matugen-starship.toml"

tmpfile="$(mktemp)"

awk '
/^# MATUGEN START$/ { skip=1; next }
/^# MATUGEN END$/   { skip=0; next }
!skip
' "$STARSHIP_CONFIG" > "$tmpfile"

{
    cat "$tmpfile"
    echo
    echo "# MATUGEN START"
    cat "$PALETTE_FILE"
    echo "# MATUGEN END"
} > "$STARSHIP_CONFIG"

rm "$tmpfile"
