GenericExecuteSynth "echo '$DATA' | piper-tts --model /usr/share/piper-voices/$VOICE --output_raw | aplay -r 22050 -f S16_LE -c 1 -t raw -"
AddVoice "en_US" "MALE1" "en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx"
DefaultVoice "en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx"
