hl.on("hyprland.start", function()
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("dbus-update-activation-environment --all")
	hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("~/.config/scripts/waybar-watch")
	hl.exec_cmd("hyprpaper & swaync")
	hl.exec_cmd("swayosd-server -s ~/.config/swayosd/style.css")
	hl.exec_cmd("nm-applet & blueman-applet")
	hl.exec_cmd("wleave --service")
	hl.exec_cmd("udiskie --appindicator")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("~/projects/cliphist-ui/target/release/clipboard-ui --service")
end)
