#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#   

foreground = "{{colors.on_background.default.hex}}"
background = "{{colors.background.default.hex}}"
accent = "{{colors.tertiary.default.hex}}"
