-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#101418",
  base01 = "#0b0f12",
  base02 = "#181c20",
  base03 = "#42474e",
  base04 = "#c2c7cf",
  base05 = "#e0e2e8",
  base06 = "#2d3135",
  base07 = "#36393e",

  base08 = "#c6addf",
  base09 = "#d3bfe6",
  base0A = "#b9c8da",
  base0B = "#9bcbfa",
  base0C = "#4f4061",
  base0D = "#0d4a73",
  base0E = "#3a4857",
  base0F = "#98aec8",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#0d4a73',
  fg = '#cee5ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#ad88d1',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8c9198',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d3bfe6',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b9c8da',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#2f628c',
})