-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#0f1512",
  base01 = "#090f0d",
  base02 = "#171d1b",
  base03 = "#3f4945",
  base04 = "#bfc9c4",
  base05 = "#dee4e0",
  base06 = "#2b322f",
  base07 = "#343b38",

  base08 = "#96bfdc",
  base09 = "#a9cbe2",
  base0A = "#b2ccc2",
  base0B = "#87d6bd",
  base0C = "#284b5e",
  base0D = "#005141",
  base0E = "#344c44",
  base0F = "#93b8aa",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#005141',
  fg = '#a2f2d9', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#70a8cf',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#89938e',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a9cbe2',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b2ccc2',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#106b57',
})