#!/bin/bash
funcName=`basename "$PWD"`


export $(printf "ACCESS_KEY_ID=%s SECRET_ACCESS_KEY=%s SESSION_TOKEN=%s" \
$(aws sts assume-role \
--role-arn arn:aws:iam::854348423694:role/local-backend-role \
--role-session-name $funcName-Local \
--query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
--output text))

docker run -p 9000:8080 --env AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN=$SESSION_TOKEN --env AWS_REGION='ca-central-1'  --rm -it $(docker build -q .)
